# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

permalink: "/:year/:month/:title.html"
url: "https://www.wassupy.com"

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-image-size
  - jekyll-environment-variables

jekyll-archives:
  enabled:
    - categories
    - month
    - year
  layouts:
    category: category_index
    month: category_index
    year: category_index
  permalinks:
    category: "/search/label/:name/" # these exist primarily to catch old Blogger-style urls
    month: "/:year/:month/"
    year: "/:year/"

sass:
  load_paths:
    - assets
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - .git
  - .github
  - .gitignore
  - README.md